format_version: 10
pipelines:
  helm-charts:
    group: kubernetes
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/raghudevopsb77/roboshop-kubernetes
        shallow_clone: false
        auto_update: true
        branch: main
        includes:
          - src/**/*.*
    stages:
    - install:
        fetch_materials: true
        approval:
            type: manual
        jobs:
          install:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments: [ "helm-dev.sh", "install" ]
            - exec:
                command: bash
                arguments: [ "helm-prod.sh", "install" ]
    - uninstall:
        fetch_materials: true
        approval:
            type: manual
        jobs:
          uninstall:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments: [ "helm.sh", "uninstall" ]



